# Generated by Django 5.2.10 on 2026-02-05 11:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('operation', models.CharField(max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('changes', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('full_fields_after', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id', '-version'], name='audit_audit_resourc_ab41d1_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_e59c15_idx')],
                'unique_together': {('resource_type', 'resource_id', 'version')},
            },
        ),
    ]
