# Generated by Django 5.2.10 on 2026-02-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_message_alter_audithistory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attempt_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
